USE	Student_Management
GO

CREATE TABLE FACULTY
(
	ID VARCHAR(50) PRIMARY KEY,
	NAME NVARCHAR(100),
	YEAR_ESTABLISH INT
)
GO

CREATE TABLE COURSE
(
	ID VARCHAR(50) PRIMARY KEY,
	YEAR_BEGIN INT,
	YEAR_END INT
)
GO

CREATE TABLE PROGRAM
(
	ID VARCHAR(50) PRIMARY KEY,
	NAME NVARCHAR(100),
)
GO

CREATE TABLE CLASS
(
	ID VARCHAR(50) PRIMARY KEY,
	ID_FACULTY VARCHAR(50),
	ID_COURSE	VARCHAR(50),
	ID_PROGRAM VARCHAR(50),
	ODER_NUM INT
	FOREIGN KEY (ID_FACULTY) REFERENCES FACULTY(ID),
	FOREIGN KEY (ID_COURSE) REFERENCES COURSE(ID),
	FOREIGN KEY (ID_PROGRAM) REFERENCES PROGRAM(ID)
)
GO

CREATE TABLE STUDENT
(
	ID VARCHAR(50) PRIMARY KEY,
	ID_CLASS VARCHAR(50),
	NAME NVARCHAR,
	YEAR_BIRTH INT,
	ETHIC NVARCHAR(100),
	FOREIGN KEY (ID_CLASS) REFERENCES CLASS(ID)
)
GO

CREATE TABLE SUBJECT
(
	ID VARCHAR(50) PRIMARY KEY,
	ID_FACULTY VARCHAR(50),
	NAME NVARCHAR(200),
	FOREIGN KEY (ID_FACULTY) REFERENCES FACULTY(ID)
)
GO

CREATE TABLE RESULT
(
	ID_STUDENT VARCHAR(50),
	ID_SUBJECT VARCHAR(50),
	TEST_TIME INT,
	SCORE FLOAT
	PRIMARY KEY (ID_STUDENT, ID_SUBJECT, TEST_TIME),

	FOREIGN KEY (ID_STUDENT) REFERENCES STUDENT(ID),
	FOREIGN KEY (ID_SUBJECT) REFERENCES SUBJECT(ID)
)
GO

CREATE TABLE DETAIL_PROGRAM
(
	ID_PROGRAM VARCHAR(50),
	ID_FACULTY VARCHAR(50),
	ID_SUBJECT VARCHAR(50),
	YEAR INT,
	SEMESTER INT,
	THEORY_LESSON INT,
	PRACTICE_LESSON INT, 
	CREDITS INT
	PRIMARY KEY(ID_PROGRAM, ID_FACULTY, ID_SUBJECT, YEAR),

	FOREIGN KEY (ID_PROGRAM) REFERENCES PROGRAM(ID),
	FOREIGN KEY (ID_FACULTY) REFERENCES FACULTY(ID),
	FOREIGN KEY (ID_SUBJECT) REFERENCES SUBJECT(ID)
)
GO